BEGIN;

TRUNCATE TABLE appellation RESTART IDENTITY CASCADE;

INSERT INTO appellation (label) VALUES ('Côtes de Bordeaux'),
('Canon Fronsac'),
('Bordeaux supérieur'),
('Côtes de Blaye'),
('Blaye'),
('Côtes de Bourg'),
('Entre-deux-mers'),
('Graves'),
('Lalande-de-Pomerol'),
('Margaux'),
('Montagne-Saint-Emilion'),
('Pessac-Léognan'),
('Saint-Emilion'),
('Saint-Estèphe'),
('Saint-Julien'),
('Bordeaux'),
('Fronsac'),
('Graves de Vayres'),
('Haut-Médoc'),
('Listrac-Médoc'),
('Lussac-Saint-Emilion'),
('Médoc'),
('Moulis'),
('Pauillac'),
('Pomerol'),
('Puisseguin-Saint-Emilion'),
('Bourgogne aligoté'),
('Chablis'),
('Côtes de Beaune'),
('Irancy'),
('Meursault'),
('Petit Chablis'),
('Pouilly-Fuissé'),
('Pouilly-Fumé'),
('Corbières'),
('Fitou'),
('Minervois'),
('Saint-Nicolas-de-Bourgueil'),
('Muscadet Sèvre et Maine'),
('Sancerre'),
('Touraine'),
('Valençay'),
('Muscadet'),
('Vouvray'),
('Côtes de Provence'),
('Bandol'),
('Tavel'),
('Châteauneuf-du-Pape'),
('Côtes du Rhône'),
('Côtes du Rhône Villages'),
('Crozes-Hermitage'),
('Rasteau'),
('Vacqueyras'),
('Côte Rôtie'),
('Gigondas'),
('Lirac'),
('Saint-Joseph'),
('Rousette de Savoie'),
('Apremont'),
('Bergerac'),
('Buzet'),
('Côtes de Bergerac'),
('Côtes du Marmandais'),
('Gaillac'),
('Pécharmant'),
('Cahors'),
('Fronton'),
('Madiran'),
('Riesling'),
('Alsace-Pinot Noir'),
('Hospices de Beaune'),
('Hautes Côtes de Beaune'),
('Menetou-Salon'),
('Picpoul de Pinet');

COMMIT;
